<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11592" started-at="2022-09-28T11:16:52Z" finished-at="2022-09-28T11:17:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11592" started-at="2022-09-28T11:16:52Z" finished-at="2022-09-28T11:17:04Z">
      <class name="org_htmlreportt.orenge1">
        <test-method status="PASS" signature="befclass()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="befclass" is-config="true" duration-ms="5035" started-at="2022-09-28T11:16:52Z" finished-at="2022-09-28T11:16:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befclass -->
        <test-method status="PASS" signature="befmet()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="befmet" is-config="true" duration-ms="0" started-at="2022-09-28T11:16:57Z" finished-at="2022-09-28T11:16:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befmet -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="test1" duration-ms="2894" started-at="2022-09-28T11:16:57Z" finished-at="2022-09-28T11:17:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org_htmlreportt.orenge1.test1(orenge1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="aftmet(org.testng.ITestResult)[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="aftmet" is-config="true" duration-ms="14" started-at="2022-09-28T11:17:00Z" finished-at="2022-09-28T11:17:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test1 status=FAILURE method=orenge1.test1()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmet -->
        <test-method status="PASS" signature="test2()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="test2" duration-ms="2162" started-at="2022-09-28T11:17:00Z" finished-at="2022-09-28T11:17:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="befmet()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="befmet" is-config="true" duration-ms="0" started-at="2022-09-28T11:17:00Z" finished-at="2022-09-28T11:17:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befmet -->
        <test-method status="PASS" signature="aftmet(org.testng.ITestResult)[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="aftmet" is-config="true" duration-ms="2" started-at="2022-09-28T11:17:02Z" finished-at="2022-09-28T11:17:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test2 status=SUCCESS method=orenge1.test2()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmet -->
        <test-method status="PASS" signature="aftcl()[pri:0, instance:org_htmlreportt.orenge1@73ad2d6]" name="aftcl" is-config="true" duration-ms="1447" started-at="2022-09-28T11:17:02Z" finished-at="2022-09-28T11:17:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftcl -->
      </class> <!-- org_htmlreportt.orenge1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
